<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Exception-Handler Syntax</title>
<style>
table th { border: 1px solid; }
table td { border: 1px solid; }
</style>
</head>
<body>
<hr />
<h2>description: The __try and __except keywords are used to construct a frame-based exception handler. The following example shows the structure of an exception handler.
ms.assetid: 1ea2c7f7-f920-4c72-bc62-4eb5e8d70790
title: Exception-Handler Syntax
ms.topic: article
ms.date: 05/31/2018</h2>
<h1>Exception-Handler Syntax</h1>
<p>The <strong>__try</strong> and <strong>__except</strong> keywords are used to construct a frame-based exception handler. The following example shows the structure of an exception handler.</p>
<pre lang="C++"><code>__try 
{
    // guarded body of code 
 
} 
__except (filter-expression) 
{ 
    // exception-handler block 
 
}
</code></pre>
<p>Note that the <strong>__try</strong> block and the exception-handler block require braces ({}). Using a <strong>goto</strong> statement to jump into the body of a <strong>__try</strong> block or into an exception-handler block is not permitted. This rule applies to both exception handlers and termination handlers.</p>
<p>The <strong>__try</strong> block contains the guarded body of code that the exception handler protects. A function can have any number of exception handlers, and these exception-handling statements can be nested within the same function or in different functions. If an exception occurs within the <strong>__try</strong> block, the system takes control and begins the search for an exception handler. For a detailed description of this search, see <a href="exception-handling.html">Exception Handling</a>.</p>
<p>The exception handler receives only exceptions that occur within a single thread. This means that if a <strong>__try</strong> block contains a call to the <a href="/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa"><strong>CreateProcess</strong></a> or <a href="/windows/win32/api/processthreadsapi/nf-processthreadsapi-createthread"><strong>CreateThread</strong></a> function, exceptions that occur within the new process or thread are not dispatched to this handler.</p>
<p>The system evaluates the filter expression of each exception handler guarding the code in which the exception occurred until either the exception is handled or there are no more handlers. A filter expression must be evaluated as one of the three following values.</p>
<table>
<thead>
<tr>
<th>Value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>EXCEPTION_EXECUTE_HANDLER</strong></td>
<td>The system transfers control to the exception handler, and execution continues in the stack frame in which the handler is found.</td>
</tr>
<tr>
<td><strong>EXCEPTION_CONTINUE_SEARCH</strong></td>
<td>The system continues to search for a handler.</td>
</tr>
<tr>
<td><strong>EXCEPTION_CONTINUE_EXECUTION</strong></td>
<td>The system stops its search for a handler and returns control to the point at which the exception occurred. If the exception is noncontinuable, this results in an <strong>EXCEPTION_NONCONTINUABLE_EXCEPTION</strong> exception.</td>
</tr>
</tbody>
</table>
<p>Â </p>
<p>The filter expression is evaluated in the context of the function in which the exception handler is located, even though the exception may have occurred in a different function. This means that the filter expression can access the function's local variables. Similarly, the exception-handler block can access the local variables of the function in which it is located.</p>
<p>For more examples, see <a href="using-an-exception-handler.html">Using an Exception Handler</a>.</p>
<p>For more information about filter expressions and filter functions, see <a href="frame-based-exception-handling.html">Frame-based Exception Handling</a>.</p>
<p>Â </p>
<p>Â </p>
</body>
