<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Termination-Handler Syntax</title>
<style>
table th { border: 1px solid; }
table td { border: 1px solid; }
</style>
</head>
<body>
<hr />
<h2>description: The __try and __finally keywords are used to construct a termination handler. The following example shows the structure of a termination handler.
ms.assetid: fbaf8890-2516-4b60-be57-464f91f2a38a
title: Termination-Handler Syntax
ms.topic: article
ms.date: 05/31/2018</h2>
<h1>Termination-Handler Syntax</h1>
<p>The <strong>__try</strong> and <strong>__finally</strong> keywords are used to construct a termination handler. The following example shows the structure of a termination handler.</p>
<pre lang="C++"><code>__try 
{ 
    // guarded body of code 
 
} 
__finally 
{ 
    // __finally block 
 
}
</code></pre>
<p>For examples, see <a href="using-a-termination-handler.html">Using a Termination Handler</a>.</p>
<p>As with the exception handler, both the <strong>__try</strong> block and the <strong>__finally</strong> block require braces ({}), and using a <strong>goto</strong> statement to jump into either block is not permitted.</p>
<p>The <strong>__try</strong> block contains the guarded body of code that is protected by the termination handler. A function can have any number of termination handlers, and these termination-handling blocks can be nested within the same function or in different functions.</p>
<p>The <strong>__finally</strong> block is executed whenever the flow of control leaves the <strong>__try</strong> block. However, the <strong>__finally</strong> block is not executed if you call any of the following functions within the <strong>__try</strong> block: <a href="/windows/win32/api/processthreadsapi/nf-processthreadsapi-exitprocess"><strong>ExitProcess</strong></a>, <a href="/windows/win32/api/processthreadsapi/nf-processthreadsapi-exitthread"><strong>ExitThread</strong></a>, or <strong>abort</strong>.</p>
<p>The <strong>__finally</strong> block is executed in the context of the function in which the termination handler is located. This means that the <strong>__finally</strong> block can access that function's local variables. Execution of the <strong>__finally</strong> block can terminate by any of the following means.</p>
<ul>
<li>Execution of the last statement in the block and continuation to the next instruction</li>
<li>Use of a control statement (<strong>return</strong>, <strong>break</strong>, <strong>continue</strong>, or <strong>goto</strong>)</li>
<li>Use of <strong>longjmp</strong> or a jump to an exception handler</li>
</ul>
<p>If execution of the <strong>__try</strong> block terminates because of an exception that invokes the exception-handling block of a frame-based exception handler, the <strong>__finally</strong> block is executed before the exception-handling block is executed. Similarly, a call to the <strong>longjmp</strong> C run-time library function from the <strong>__try</strong> block causes execution of the <strong>__finally</strong> block before execution resumes at the target of the <strong>longjmp</strong> operation. If <strong>__try</strong> block execution terminates due to a control statement (<strong>return</strong>, <strong>break</strong>, <strong>continue</strong>, or <strong>goto</strong>), the <strong>__finally</strong> block is executed.</p>
<p>The <a href="abnormaltermination.html"><strong>AbnormalTermination</strong></a> function can be used within the <strong>__finally</strong> block to determine whether the <strong>__try</strong> block terminated sequentially â€” that is, whether it reached the closing brace (}). Leaving the <strong>__try</strong> block because of a call to <strong>longjmp</strong>, a jump to an exception handler, or a <strong>return</strong>, <strong>break</strong>, <strong>continue</strong>, or <strong>goto</strong> statement, is considered an abnormal termination. Note that failure to terminate sequentially causes the system to search through all stack frames in reverse order to determine whether any termination handlers must be called. This can result in performance degradation due to the execution of hundreds of instructions.</p>
<p>To avoid abnormal termination of the termination handler, execution should continue to the end of the block. You can also execute the <strong>__leave</strong> statement. The <strong>__leave</strong> statement allows for immediate termination of the <strong>__try</strong> block without causing abnormal termination and its performance penalty. Check your compiler documentation to determine if the <strong>__leave</strong> statement is supported.</p>
<p>If execution of the <strong>__finally</strong> block terminates because of the <strong>return</strong> control statement, it is equivalent to a <strong>goto</strong> to the closing brace in the enclosing function. Therefore, the enclosing function will return.</p>
<p>Â </p>
<p>Â </p>
</body>
